# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-10 08:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0002_auto_20171229_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='read_posts',
            field=models.ManyToManyField(related_name='read', to='blogapp.Post'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='subscribers',
            field=models.ManyToManyField(related_name='subs', to='blogapp.ProfileUser'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
