# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-01 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20180101_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='read_posts',
            field=models.ManyToManyField(related_name='read', to='blogapp.Post'),
        ),
    ]
